version: '2'
services: 
  dbgame:
    container_name: dbgame
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwdgame
      MYSQL_DATABASE: battleboat
      MYSQL_USER: battleuser
      MYSQL_PASSWORD: battlepass
    restart: always
    networks:
      - game
 
  battlegame:
    container_name: battlegame
    image: franckjunior/fake-backend:travis
    volumes:
      - ./battleboat:/etc/backend/static
    depends_on:
      - dbgame
    ports:
      - 8282:3000
    environment:
      DATABASE_HOST: dbgame
      DATABASE_PORT: 3306
      DATABASE_USER: battleuser
      DATABASE_PASSWORD: battlepass
      DATABASE_NAME: battleboat
    restart: always
    networks: 
      - game
      
volumes:
  mysql_data: 
    

networks:
  game:
    
